# Use root/example user/password credentials
version: '3.1'

services:
  php:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8101:8101
    volumes:
      - ./app:/var/www/html/
